- name: Bind9 | Create records via DDNS in {{ zone_item.key }}
  community.general.nsupdate:
    # server parameters
    key_name: "{{ zone_item.value.key_name }}"
    key_algorithm: "{{ zone_item.value.key_algorithm | default('hmac-md5') }}"
    key_secret: "{{ zone_item.value.key_secret }}"
    server: "{{ zone_item.value.server | default('127.0.0.1') }}"
    port: "{{ zone_item.value.port | default(53) }}"
    protocol: "{{ zone_item.value.protocol | default('tcp') }}"
    # zone
    zone: "{{ zone_item.value.zone }}"
    # zone records parameters
    record: "{{ item.record }}"
    type: "{{ item.type | default('A') }}"
    value: "{{ item.value }}"
    ttl: "{{ item.ttl | default(zone_item.value.default_ttl | default(3600)) }}"
    state: "{{ item.state | default('present') }}"
  with_list: "{{ zone_item.value.rrs }}"
  loop_control:
    label: >-
      Record: {{ item.record }}, Type: {{ item.type }}, Value: {{ item.value }},
      TTL: {{ item.ttl | default(zone_item.value.default_ttl | default(3600)) }}
  when:
    - (zone_item.value.get('restrict_to_server', true) | bool
        and (zone_item.value.get('server', '127.0.0.1') in ansible_all_ipv4_addresses
              or zone_item.value.get('server', '127.0.0.1') in ansible_all_ipv6_addresses))
      or not zone_item.value.get('restrict_to_server', true) | bool
  register: bind9_ddns_zone_change
  tags:
    - config
    - zones
    - bind9
    - bind9-config
    - bind9-zones
    - bind9-zones-ddns

- name: Bind9 | Sync zone file with rndc sync - {{ zone_item.key }} # noqa no-changed-when
  ansible.builtin.command:
    cmd: "rndc sync {{ zone_item.value.zone }}"
  when:
    - bind9_ddns_zone_change is changed
    - bind9_ddns_zone_change is succeeded
    # rndc without extra configuration most probably will only run successfully
    # on the same server where zone is hosted i.e. on the zone master server
    - zone_item.value.get('server', '0.0.0.0') in ansible_all_ipv4_addresses
      or zone_item.value.get('server', '0.0.0.0') in ansible_all_ipv6_addresses
  register: bind9_rndc_output
  ignore_errors: true
  tags:
    - config
    - zones
    - bind9
    - bind9-config
    - bind9-zones
    - bind9-zones-ddns

- name: Bind9 | rndc message for zone {{ zone_item.key }}
  ansible.builtin.debug:
    msg:
      - "stdout: {{ bind9_rndc_output.get('stdout', '') | replace('\n', ' ') }}"
      - "stderr: {{ bind9_rndc_output.get('stderr', '') | replace('\n', ' ') }}"
  # show rndc output when there is something in stdout or stderr or when return code is not 0
  when:
    - bind9_rndc_output is defined
    - not bind9_rndc_output is skipped
    - bind9_rndc_output.stdout
      or bind9_rndc_output.stderr
      or bind9_rndc_output.rc != 0
  tags:
    - config
    - zones
    - bind9
    - bind9-config
    - bind9-zones
    - bind9-zones-ddns
